development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 10
  username: root
  password: 
  socket: /tmp/mysql.sock
  database: playground_dev

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 10
  username: root
  password: 
  socket: /tmp/mysql.sock
  database: playground_test
  
production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 10
  username: root
  password: 
  socket: /tmp/mysql.sock
  database: playground_prod